jenkins:
  systemMessage: "Automating Jenkins Setup using Docker and Jenkins Configuration as Code\n\n"
  remotingSecurity:
   enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
unclassified:
  location:
    url: http://127.0.0.1:8080/
jobs:
  - file: /usr/local/seedjob.groovy

plugin:
    repositories:
      - id: "default"
        url: "https://updates.jenkins.io/update-center.json"

    installations:
      - name: "pipeline"
        source:
          plugin: "pipeline"
        version: "2.7"

      - name: "git"
        source:
          plugin: "git"
        version: "4.11.0"