jenkins:
  systemMessage: "Automating Jenkins Setup using Docker and Jenkins Configuration as Code\n\n"
  remotingSecurity:
   enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
unclassified:
  location:
    url: http://127.0.0.1:8080/
jobs:
  - file: /usr/local/seedjob.groovy

unclassified:
  # ... other JCasC configuration ...

  # Add plugins here
  plugin:
    repositories:
      - id: "default"
        url: "https://updates.jenkins.io/update-center.json"

    installations:
      - name: "ant"
        source:
          plugin: "ant"
        version: "latest"

      - name: "antisamy-markup-formatter"
        source:
          plugin: "antisamy-markup-formatter"
        version: "latest"

      - name: "build-timeout"
        source:
          plugin: "build-timeout"
        version: "latest"

      - name: "cloudbees-folder"
        source:
          plugin: "cloudbees-folder"
        version: "latest"

      - name: "configuration-as-code"
        source:
          plugin: "configuration-as-code"
        version: "latest"

      - name: "credentials-binding"
        source:
          plugin: "credentials-binding"
        version: "latest"

      - name: "email-ext"
        source:
          plugin: "email-ext"
        version: "latest"

      - name: "git"
        source:
          plugin: "git"
        version: "latest"

      - name: "github-branch-source"
        source:
          plugin: "github-branch-source"
        version: "latest"

      - name: "gradle"
        source:
          plugin: "gradle"
        version: "latest"

      - name: "ldap"
        source:
          plugin: "ldap"
        version: "latest"

      - name: "mailer"
        source:
          plugin: "mailer"
        version: "latest"

      - name: "matrix-auth"
        source:
          plugin: "matrix-auth"
        version: "latest"

      - name: "pam-auth"
        source:
          plugin: "pam-auth"
        version: "latest"

      - name: "pipeline-github-lib"
        source:
          plugin: "pipeline-github-lib"
        version: "latest"

      - name: "pipeline-stage-view"
        source:
          plugin: "pipeline-stage-view"
        version: "latest"

      - name: "ssh-slaves"
        source:
          plugin: "ssh-slaves"
        version: "latest"

      - name: "timestamper"
        source:
          plugin: "timestamper"
        version: "latest"

      - name: "workflow-aggregator"
        source:
          plugin: "workflow-aggregator"
        version: "latest"

      - name: "ws-cleanup"
        source:
          plugin: "ws-cleanup"
        version: "latest"

      - name: "job-dsl"
        source:
          plugin: "job-dsl"
        version: "latest"

      - name: "blueocean"
        source:
          plugin: "blueocean"
        version: "latest"

      - name: "authorize-project"
        source:
          plugin: "authorize-project"
        version: "latest"
